import React from 'react';
import './Input.css';

const propTypes = {
	
};

class Input extends React.Component {
	render () {
		return <div className='Input'>
			<h1>Component: Input</h1>
			<h3>Generated by react-mogen</h3>
		</div>;
	}
}

Input.propTypes = propTypes;
export default Input;