import React from 'react';
import './Title.css';

const propTypes = {
	
};

const Title = (props) => {
	return <div className='Title'>
		<h1>Stateless component: Title</h1>
		<h3>Generated by react-mogen</h3>
	</div>
};

Title.propTypes = propTypes;
export default Title;