import React from 'react';
import './Header.css';

const propTypes = {
	
};

class Header extends React.Component {
	render () {
		return <div className='Header'>
			<h1>Component: Header</h1>
			<h3>Generated by react-mogen</h3>
		</div>;
	}
}

Header.propTypes = propTypes;
export default Header;