import React from 'react';
import './Footer.css';

const propTypes = {
	
};

class Footer extends React.Component {
	render () {
		return <div className='Footer'>
			<h1>Component: Footer</h1>
			<h3>Generated by react-mogen</h3>
		</div>;
	}
}

Footer.propTypes = propTypes;
export default Footer;